version: '3.8'

services:
  backend:
    build:
      context: ./sharezilla-main
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/sharezilla
      - SPRING_DATASOURCE_USERNAME=sakthi
      - SPRING_DATASOURCE_PASSWORD=5326
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=sakthi
      - POSTGRES_PASSWORD=5326
      - POSTGRES_DB=sharezilla
    volumes:
      - sharezilla_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  sharezilla_db_data:
